### ISSUE TITLE
no verification email sent- can not get api key

### ISSUE THREAD

**Issue by jj-github-jj** [DeepGenX/CodeGenX#42] opened 2022-12-20 14:51 UTC
tried signing up via web site but didnt get any email for verification so no api  key

**Comment by smart2pet** [comment] 2022-12-22 04:57
yeah

**Comment by smart2pet** [comment] 2022-12-22 04:57
look at Issue #32

**Comment by ns-jlopez** [comment] 2023-01-02 09:31
same here

**Comment by voskresenskiianton** [comment] 2023-02-06 20:18
can't get an api key

**Comment by Matthias1590** [comment] 2023-02-07 14:03
Duplicate of #32

**Closed as not planned** 2023-02-07 14:02 UTC
