### ISSUE TITLE
Request of API key 

### ISSUE THREAD

**Issue by AlbertFlorinus** [DeepGenX/CodeGenX#22] opened 2022-02-17 22:37 UTC
I've requested an API key by submitting my email, I've been looking everywhere but it doesn't seem to send any verification link (gmail).

**Comment by Aryagm** [comment] 2022-02-19 15:37
Hi,

Sorry for the late response.

We were having some issues with our servers a couple of days ago. The problem is now fixed.

Could you please try again and let me know if it works?

Thanks,
Arya

**Comment by AlbertFlorinus** [comment] 2022-02-19 17:08
@Aryagm
It's working now, thanks!

**Closed** 2022-02-19 17:16 UTC

**Comment by smart2pet** [comment] 2022-11-18 11:32
But I cant get the key now.It was happened again.
